lib/easy_timer_web/router.ex
defmodule Web.Router do
  use Web, :router
  # import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html", "text"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Web.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Web do
    pipe_through :browser

    # live "/", Setup
    # live "/quick", Setup
    # live "/custom", Setup
    # live "/pagelive", PageLive, :index
    get "/live/:scenario_id", TimerController, :show

    get "/", SetupController, :index
    get "/quick", SetupController, :quick
    post "/quick", SetupController, :setup_quick
    get "/custom", SetupController, :custom
    post "/custom", SetupController, :setup_custom
    get "/setup_error", SetupController, :error
  end

  # Other scopes may use custom stacks.
  # scope "/api", Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Web.Telemetry
    end
  end
end

lib/easy_timer_web/controllers/setup_controller.ex
defmodule Web.SetupController do
  use Web, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def quick(conn, _params) do
    render(conn, "quick.html")
  end

  def custom(conn, _params) do
    render(conn, "custom.html")
  end

  def setup_quick(conn, %{"hours" => hours, "minutes" => mins, "seconds" => secs}) do
    case EasyTimer.create(:quick, %{
           duration_hours: hours,
           duration_minutes: mins,
           duration_seconds: secs
         }) do
      %{scenario_id: scenario_id, admin_pin: admin_pin} ->
        host = "/live/"

        conn
        |> Plug.Conn.put_session("easytimer-admin-#{scenario_id}", true)
        |> Plug.Conn.configure_session(renew: true)
        |> render("success.html",
          page_title: "Quick Timer",
          admin_pin: admin_pin,
          host: host,
          scenario_id: scenario_id
        )

      {:error, %{type: "phase_init_errors", errors: errors}} when is_list(errors) ->
        render(conn, "quick_error.html", phase_errors: errors)
    end
  end

  def setup_custom(conn, %{"file" => file}) do
    case EasyTimer.create(:custom, %{file: file.path}) do
      %{scenario_id: scenario_id, admin_pin: admin_pin} ->
        host = "live/"

        conn
        |> Plug.Conn.put_session("easytimer-admin-#{scenario_id}", true)
        |> Plug.Conn.configure_session(renew: true)
        |> render("success.html",
          page_title: "Custom Timer",
          admin_pin: admin_pin,
          host: host,
          scenario_id: scenario_id
        )

      {:error, %{type: "phase_init_errors", errors: errors}} when is_list(errors) ->
        IO.inspect(errors)

        render(conn, "custom_error.html",
          phase_errors: [
            "There's a bunch of phase errors I can't list right now. Check your file."
          ]
        )

      {:error, %{type: "file_error", errors: nil}} ->
        render(conn, "custom_error.html",
          file_errors: ["Cannot read file. Please ensure this is a properly formatted CSV file."]
        )

      {:error, %{type: "parsing_errors", errors: errors}} ->
        IO.inspect(errors)

        render(conn, "custom_error.html",
          file_errors: ["Cannot parse file. Please ensure this is a properly formatted CSV file."]
        )
    end
  end
end

lib/easy_timer_web/live/_old_setup/setup.ex
# defmodule Web.Setup do
#   use Phoenix.LiveView
#   alias Web.Setup

#   @defaults %{timer_type: nil}

#   def render(assigns) do
#     render_component(assigns)
#   end

#   def render_component(%{timer_type: type} = assigns) do
#     [id, component] =
#       case type do
#         nil -> [:home, Setup.Home]
#         "quick" -> [:home, Setup.Quick]
#         "custom" -> [:home, Setup.Custom]
#       end

#     ~L"""
#     <div><%= live_component @socket, component, id: id, timer_type: @timer_type %></div>
#     """
#   end

#   def mount(_params, _session, socket) do
#     {:ok, assign(socket, Map.merge(@defaults, socket.assigns))}
#   end

#   def handle_event("update_timer_type", %{"type" => type}, socket) do
#     socket = assign(socket, :timer_type, type)
#     {:noreply, push_patch(socket, to: "/#{type}", replace: true)}
#   end

#   def handle_params(_params, _uri, socket) do
#     {:noreply, socket}
#   end
# end

lib/easy_timer_web/views/setup_view.ex
defmodule Web.SetupView do
  use Web, :view
end

lib/easy_timer_web/templates/setup/custom.html.eex
<div class="mx-auto pt-2 dbb">
  <%= render("nav.html", conn: @conn, page_title: "Custom Timer") %>
  <%= form_for @conn, Routes.setup_path(@conn, :setup_custom), [multipart: true], fn f -> %>

    <div class="mx-auto my-14 w-7/12 sm:w-5/12 md:w-4/12 lg:w-3/12 dbr">
      <p class="mt-4 text-xl dbb">Please upload a CSV file.</p>
      <a href="/templates/custom_timer_template.csv" style="text-decoration: underline;" class="mb-4">Here's a template you can use.</a>
      <%= file_input f, :file, class: "my-8 dbb" %>
    </div>
    <div class="mx-auto flex justify-center dbr">
      <%= submit "Upload", class: "btn-lg btn-indigo-white w-40 dbb p-4" %>
    </div>

  <% end %>
</div>

lib/easy_timer_web/templates/setup/custom_error.html.eex
<div class="mx-auto pt-2 dbb">
  <%= render("nav.html", conn: @conn, page_title: "Custom Timer") %>
  <div class="mx-auto text-center my-16 w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
    <p class="text-5xl leading-none"><strong>Uh oh!</strong></p>
    <p class="text-2xl my-4">Please provide:</p>
    <ul>
      <%= for item <- @phase_errors || @file_errors do %>
        <li class="my-8"><%= item.message %></li>
      <% end %>
    </ul>
  </div>
  <div class="mx-auto flex justify-center w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
    <button
      onclick="window.location.href = '<%= Routes.setup_path(@conn, :custom) %>';"
      class="btn-lg btn-pink-white sm:text-3xl">
      Edit
    </button>
  </div>
</div>

lib/easy_timer_web/templates/setup/index.html.eex
<div class="pt-4 xs:pt-16 sm:pt-24 lg:pt-12 dbb">
  <img class="dbg mx-auto icon-timer" src="/images/timer1.svg" alt="timer">
  <h1 class="my-2 xs:my-4 sm:my-6 text-5xl sm:text-6xl dbg text-center" style="font-style: italic">
    Easy Timer
  </h1>
  <div class="mx-auto w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
    <button
      onclick="window.location.href = '<%= Routes.setup_path(@conn, :quick) %>';"
      class="btn-lg btn-indigo-white mb-4 sm:text-3xl">
      Quick
    </button>
    <button
      onclick="window.location.href = '<%= Routes.setup_path(@conn, :custom) %>';"
      class="btn-lg btn-indigo-white sm:text-3xl">
      Custom
    </button>
  </div>
</div>

lib/easy_timer_web/templates/setup/index.text.eex
I don't have operable links for you.
Please visit the interactive site.

Thank you!

lib/easy_timer_web/templates/setup/nav.html.eex
<div class="relative dbr">
  <div class="absolute h-full sm:ml-28 md:ml-44 lg:ml-76 xl:ml-96 2xl:ml-112">
    <button
      class="btn-back btn-indigo-white"
      onClick="window.location.href = '<%= Routes.setup_path(@conn, :index) %>';">
      Back
    </button>
  </div>
  <h1 class="text-center text-4xl"><%= @page_title %></h1>
</div>

lib/easy_timer_web/templates/setup/quick.html.eex
<div class="mx-auto pt-2 dbb">
  <%= render("nav.html", conn: @conn, page_title: "Quick Timer") %>
  <%= form_for @conn, Routes.setup_path(@conn, :setup_quick), fn f -> %>
    <div class="mx-auto my-8 grid grid-cols-2 dbr">

      <div class="pr-4 flex flex-col justify-center dbb">
        <%= label f, :hours, class: "leading-none text-right text-3xl" %>
        <p class="text-sm text-right text-red-500">Max 24</p>
      </div>
      <div>
        <%= number_input f, :hours, class: "pl-8 text-5xl w-24", min: "0", max: "24", value: "00" %>
      </div>

      <div class="pr-4 flex flex-col justify-center dbb">
        <%= label f, :minutes, class: "leading-none text-right text-3xl" %>
        <p class="text-sm text-right text-red-500">0 - 59</p>
      </div>
      <%= number_input f, :minutes, class: "pl-8 text-5xl w-24", min: "0", max: "59", value: "05" %>

      <div class="pr-4 flex flex-col justify-center dbb">
        <%= label f, :seconds, class: "leading-none text-right text-3xl" %>
        <p class="text-sm text-right text-red-500">0 - 59</p>
      </div>
      <%= number_input f, :seconds, class: "pl-8 text-5xl w-24", min: "0", max: "59", value: "00" %>

    </div>

    <div class="mx-auto flex justify-center dbr">
      <%= submit "Create", class: "btn-lg btn-green-white w-40 p-4" %>
    </div>
  <% end %>

</div>

lib/easy_timer_web/templates/setup/quick_error.html.eex
<div class="mx-auto pt-2 dbb">
  <%= render("nav.html", conn: @conn, page_title: "Quick Timer") %>
  <div class="mx-auto text-center my-16 w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
    <p class="text-5xl leading-none"><strong>Uh oh!</strong></p>
    <p class="text-2xl my-4">Please provide:</p>
    <ul>
      <%= for item <- @phase_errors do %>
        <li class="my-8"><%= item.message %></li>
      <% end %>
    </ul>
  </div>
  <div class="mx-auto flex justify-center w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
    <button
      onclick="window.location.href = '<%= Routes.setup_path(@conn, :quick) %>';"
      class="btn-lg btn-pink-white sm:text-3xl">
      Edit
    </button>
  </div>
</div>

lib/easy_timer_web/templates/setup/success.html.eex
<div class="mx-auto pt-2 dbb">
  <%= render("nav.html", conn: @conn, page_title: @page_title) %>

    <div class="mx-auto flex flex-col justify-center my-6 w-8/12 sm:w-5/12 md:w-4/12 lg:w-3/12 dbr">
      <p class="mb-2 text-4xl text-center dbb">Success!</p>
      <p class="text-lg text-center dbb">Your timer is live at:</p>
      <p class="text-lg text-center dbb"><%= @host %></p>
      <p class="my-2 text-4xl bg-pink-300 text-center dbb"><strong><%= @scenario_id %></strong></p>
      <p class="text-lg text-center dbb">your admin pin code is:</p>
      <p class="text-4xl text-center dbb"><strong><%= @admin_pin %></strong></p>
    </div>

    <div class="flex mx-auto w-4/5 sm:w-3/5 lg:w-2/5 xl:w-4/12 2xl:w-1/4 dbr">
      <button
        class="btn-lg mr-4 text-center btn-pink-white sm:text-3xl">
        Copy Link
      </button>
      <button
        onclick="window.location.href = '<%= @host <> @scenario_id %>';"
        class="btn-lg text-center btn-green-white sm:text-3xl">
        Go
      </button>
    </div>

</div>